import './globals.css'
import { Inter } from 'next/font/google'
import CustomProvider from '@/redux/provider'
import { Toaster } from 'react-hot-toast'
import { ConfettiProvider } from '@/components/provider/confetti-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          {children}
          <ConfettiProvider />
          <Toaster position='bottom-right' />
        </CustomProvider>
      </body>
    </html>
  )
}
